server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:autdb
    username: sa
    password: sa
  jpa: database-platform:org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  application:
    name: api-rest
  health:
    config:
      enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: utubed.service@gmail.com
    password: Ar3s02!!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://cloud-eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}