server:
  port: 8082
spring:
  application:
    name: ibolletta-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  health:
    config:
      enabled: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ibollettadb
    username: sa
    password: sa
    jpa: database-platform:org.hibernate.dialect.H2Dialect
    h2:
      console:
        enabled: true
        path: /h2-console
    data:
      jpa:
        repositories:
          bootstrap-mode: default
eureka:
  client:
    serviceUrl:
      defaultZone: http://cloud-eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}