server:
  port: 8755
spring:
  application:
    name: zuul-api-gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}

