server:
  port: 8755
spring:
  application:
    name: zuul-api-gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  zipkin:
    base-url: http://zipkin:9411/
  sleuth:
    enabled: true
  rabbitmq:
    addresses: amqp://rabbitmq:5672/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}

