version: '3.2'
services:
    config-server:
        container_name: config-server
        build:
            context: ../cloud-config-server
            dockerfile: Dockerfile
        networks:
            - cloud-native-network
        expose:
            - 8888
        ports:
            - "8888:8888/tcp"
            - "8888:8888/udp"
    eureka-server:
        container_name: eureka-server
        build:
            context: ../cloud-eureka-server
            dockerfile: Dockerfile
        networks:
            - cloud-native-network
        expose:
            - 8761
        ports:
            - 8761:8761
        depends_on:
            - config-server
    api-rest:
        container_name: api-rest
        build:
            context: ../api-rest
            dockerfile: Dockerfile
        networks:
            - cloud-native-network
        expose:
            - 8081
        ports:
            - 8081:8081
        depends_on:
            - config-server
networks:
    cloud-native-network:
        driver: bridge