version: '3.2'
services:
    elasticsearch:
        build:
            context: elasticsearch/
            args:
                ELK_VERSION: $ELK_VERSION
        volumes:
            -   type: bind
                source: ./elasticsearch/config/elasticsearch.yml
                target: /usr/share/elasticsearch/config/elasticsearch.yml
                read_only: true
            -   type: volume
                source: elasticsearch
                target: /usr/share/elasticsearch/data
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            ES_JAVA_OPTS: "-Xmx256m -Xms256m"
            ELASTIC_PASSWORD: changeme
            discovery.type: single-node
        networks:
            - cloud-native-network

    logstash:
        build:
            context: logstash/
            args:
                ELK_VERSION: $ELK_VERSION
        volumes:
            -   type: bind
                source: ./logstash/config/logstash.yml
                target: /usr/share/logstash/config/logstash.yml
                read_only: true
            -   type: bind
                source: ./logstash/pipeline
                target: /usr/share/logstash/pipeline
                read_only: true
        ports:
            - "5000:5000/tcp"
            - "5000:5000/udp"
            - "9600:9600"
        environment:
            LS_JAVA_OPTS: "-Xmx256m -Xms256m"
        networks:
            - cloud-native-network
        depends_on:
            - elasticsearch
    kibana:
        build:
            context: kibana/
            args:
                ELK_VERSION: $ELK_VERSION
        volumes:
            - type: bind
              source: ./kibana/config/kibana.yml
              target: /usr/share/kibana/config/kibana.yml
              read_only: true
        ports:
            - "5601:5601"
        networks:
            - cloud-native-network
        depends_on:
            - elasticsearch
    cloud-config-server:
        build: ../cloud-config-server
        container_name: cloud-config-server
        working_dir: /cloud-config-server
        volumes:
            - ../cloud-config-server:/cloud-config-server
            - ~/.m2:/root/.m2
        networks:
            - cloud-native-network
        depends_on:
            - kibana
        expose:
            - 8888
        ports:
            - "8888:8888/tcp"
            - "8888:8888/udp"
        command: mvn clean spring-boot:run
        restart: always
    cloud-eureka-server:
        build: ../cloud-eureka-server
        working_dir: /cloud-eureka-server
        volumes:
            - ../cloud-eureka-server:/cloud-eureka-server
            - ~/.m2:/root/.m2
        networks:
            - cloud-native-network
        expose:
            - "8761"
        ports:
            - "8761:8761"
        command: mvn clean spring-boot:run
        restart: always
        depends_on:
            - cloud-config-server
    zuul-api-gateway:
        build: ../zuul-api-gateway
        working_dir: /zuul-api-gateway
        volumes:
            - ../zuul-api-gateway:/zuul-api-gateway
            - ~/.m2:/root/.m2
        networks:
            - cloud-native-network
        expose:
            - 8755
        ports:
            - 8755:8755
        command: mvn clean spring-boot:run
        restart: always
        depends_on:
            - cloud-eureka-server
    api-rest:
        build: ../api-rest
        working_dir: /api-rest
        volumes:
            - ../api-rest:/api-rest
            - ~/.m2:/root/.m2
        networks:
            - cloud-native-network
        expose:
            - 8081
        ports:
            - 8081:8081
        command: mvn clean spring-boot:run -Dspring-boot.run.arguments=--spring.cloud.config.uri=http://cloud-config-server:8888
        restart: always
        depends_on:
            - zuul-api-gateway
    ibolletta-service:
        build: ../ibolletta-service
        working_dir: /ibolletta-service
        volumes:
            - ../ibolletta-service:/ibolletta-service
            - ~/.m2:/root/.m2
        networks:
            - cloud-native-network
        expose:
            - 8082
        ports:
            - 8082:8082
        command: mvn clean spring-boot:run
        restart: always
        depends_on:
            - zuul-api-gateway
volumes:
    elasticsearch:
networks:
    cloud-native-network:
